# Generated by Django 4.2 on 2023-04-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video_url', models.URLField()),
                ('hidden_title', models.CharField(max_length=50)),
                ('hidden_video_url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quizes')),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
