# Generated by Django 4.2 on 2023-04-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quizes'),
        ),
    ]
