# Generated by Django 4.2 on 2023-04-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_video_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
                ('answer', models.CharField(choices=[(models.CharField(max_length=50), models.CharField(max_length=50)), (models.CharField(max_length=50), models.CharField(max_length=50)), (models.CharField(max_length=50), models.CharField(max_length=50)), (models.CharField(max_length=50), models.CharField(max_length=50))], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('questions', models.ManyToManyField(to='app.question')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quiz'),
        ),
        migrations.DeleteModel(
            name='Quizes',
        ),
    ]
