# Generated by Django 4.2 on 2023-04-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_studentresponse_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
